apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: py-app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: my-app
  template:
    metadata:
      labels:
        name: my-app
    spec:
      containers:
      - name: my-app
        image: us.gcr.io/iti-1-358616/my-app
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: app-cm
~                             