apiVersion: v1
kind: Service
metadata:
  name: app-lb
  namespace: py-app
spec:
  type: LoadBalancer
  selector:
    name: my-app
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30088
                                                                                     