apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: py-app
  labels:
    name: redis
spec:
  containers:
  - name: redis
    image: us.gcr.io/iti-1-358616/redis
    ports:
    - containerPort: 6379